// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ticker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// TickerClient is the client API for Ticker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TickerClient interface {
	SendTicker(ctx context.Context, in *Tick, opts ...grpc.CallOption) (*Tick, error)
}

type tickerClient struct {
	cc grpc.ClientConnInterface
}

func NewTickerClient(cc grpc.ClientConnInterface) TickerClient {
	return &tickerClient{cc}
}

func (c *tickerClient) SendTicker(ctx context.Context, in *Tick, opts ...grpc.CallOption) (*Tick, error) {
	out := new(Tick)
	err := c.cc.Invoke(ctx, "/ticker.Ticker/SendTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TickerServer is the server API for Ticker service.
// All implementations must embed UnimplementedTickerServer
// for forward compatibility
type TickerServer interface {
	SendTicker(context.Context, *Tick) (*Tick, error)
	mustEmbedUnimplementedTickerServer()
}

// UnimplementedTickerServer must be embedded to have forward compatible implementations.
type UnimplementedTickerServer struct {
}

func (UnimplementedTickerServer) SendTicker(context.Context, *Tick) (*Tick, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTicker not implemented")
}
func (UnimplementedTickerServer) mustEmbedUnimplementedTickerServer() {}

// UnsafeTickerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TickerServer will
// result in compilation errors.
type UnsafeTickerServer interface {
	mustEmbedUnimplementedTickerServer()
}

func RegisterTickerServer(s grpc.ServiceRegistrar, srv TickerServer) {
	s.RegisterService(&_Ticker_serviceDesc, srv)
}

func _Ticker_SendTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tick)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerServer).SendTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticker.Ticker/SendTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerServer).SendTicker(ctx, req.(*Tick))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ticker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ticker.Ticker",
	HandlerType: (*TickerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTicker",
			Handler:    _Ticker_SendTicker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ticker.proto",
}
